repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.13
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/NSPBot911/ty-pre-commit
    # ty version.
    rev: v0.0.12
    hooks:
      # Run the linter.
      - id: ty-check
        types_or: [ python, pyi ]
  # - repo: https://github.com/denehoffman/yamloom
  #   rev: v0.1.0
  #   hooks:
  #     - id : yamloom-sync
  #       files: ^(\.github/workflows/.*\.ya?ml|\.yamloom\.py)$
